spring:
  profiles:
    active: local
  main:
    banner-mode: off
    log-startup-info: off
logging:
  group:
    tomcat:
      - org.apache.catalina
      - org.apache.coyote
      - org.apache.tomcat
      - org.springframework.boot.web.embedded.tomcat
  level:
    tomcat: error
    web: error
    tech.ikezawa: debug